version: '#{build}'
configuration: Release
before_build:
  - nuget restore ".\EscritaPorExtenso.sln"
build:
  project: EscritaPorExtenso.sln
  publish_nuget: true
  publish_wap: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 5rJTzHnpkaJ/FIYFCJ1VZ6zzVVQaLXk5dszt8Up1cbQcKAK3GVlVOU0BRtBr1Mzh
- provider: WebDeploy
  server: https://escreverporextenso.scm.azurewebsites.net:443/msdeploy.axd?site=ESCREVERPOREXTENSO
  website: ESCREVERPOREXTENSO
  username: $ESCREVERPOREXTENSO
  password:
    secure: SLMdNXjNkAyGu6k6nDGLLEp2mcI5Qj4NhzGDBWnlL+jlwe8+fU+0PwqzGYSkKBzsAR6CXeJ3zbpNVbuqnbuZYw==
  app_offline: false
environment:
  COVERALLS_REPO_TOKEN:
    secure: JAgAiZQTZdWLL5ZPv18WI+uWChs26/bT6bZCLFde/5v7KeCtlUs9DlsknMRM+1xi
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""EscritaPorExtenso.Testes\bin\$env:CONFIGURATION\EscritaPorExtenso.Testes.dll"" /noshadow" -filter:"+[EscritaPorExtenso*]*" -filter:"-[EscritaPorExtenso.Testes]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "packages/coveralls.io.*/tools/coveralls.net.exe").ToString()

    & $coveralls --opencover opencoverCoverage.xml --full-sources